import { Inter } from 'next/font/google';
import { Josefin_Sans } from '@next/font/google';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'CAR DESIGNER',
  description: 'Generated by create next app',
};

const josefin = Josefin_Sans({
  subsets: ['latin'],
  // weight: [100, 200, 300, 400, 500, 600, 700, 800, 900],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={josefin.className}>{children}</body>
    </html>
  );
}
